export const GET_LATENCY_START = 'GET_LATENCY_START';
export const GET_LATENCY_END = 'GET_LATENCY_END';
export const GET_LATENCY_SUCCESS = 'GET_LATENCY_SUCCESS';
export const GET_LATENCY_FAILURE = 'GET_LATENCY_FAILURE';
