export const GET_UPTIME_START = 'GET_UPTIME_START';
export const GET_UPTIME_END = 'GET_UPTIME_END';
export const GET_UPTIME_SUCCESS = 'GET_UPTIME_SUCCESS';
export const GET_UPTIME_FAILURE = 'GET_UPTIME_FAILURE';

export const GET_RATE_START = 'GET_RATE_START';
export const GET_RATE_END = 'GET_RATE_END';
export const GET_RATE_SUCCESS = 'GET_RATE_SUCCESS';
export const GET_RATE_FAILURE = 'GET_RATE_FAILURE';

export const GET_RATE_AGENT_START = 'GET_RATE_AGENT_START';
export const GET_RATE_AGENT_END = 'GET_RATE_AGENT_END';
export const GET_RATE_AGENT_SUCCESS = 'GET_RATE_AGENT_SUCCESS';
export const GET_RATE_AGENT_FAILURE = 'GET_RATE_AGENT_FAILURE';

export const GET_START_TIME_START = 'GET_START_TIME_START';
export const GET_START_TIME_END = 'GET_START_TIME_END';
export const GET_START_TIME_SUCCESS = 'GET_START_TIME_SUCCESS';
export const GET_START_TIME_FAILURE = 'GET_START_TIME_FAILURE';

export const GET_HEAP_USAGE_START = 'GET_HEAP_USAGE_START';
export const GET_HEAP_USAGE_END = 'GET_HEAP_USAGE_END';
export const GET_HEAP_USAGE_SUCCESS = 'GET_HEAP_USAGE_SUCCESS';
export const GET_HEAP_USAGE_FAILURE = 'GET_HEAP_USAGE_FAILURE';

export const GET_NON_HEAP_USAGE_START = 'GET_NON_HEAP_USAGE_START';
export const GET_NON_HEAP_USAGE_END = 'GET_NON_HEAP_USAGE_END';
export const GET_NON_HEAP_USAGE_SUCCESS = 'GET_NON_HEAP_USAGE_SUCCESS';
export const GET_NON_HEAP_USAGE_FAILURE = 'GET_NON_HEAP_USAGE_FAILURE';

export const GET_ERROR_START = 'GET_ERROR_START';
export const GET_ERROR_END = 'GET_ERROR_END';
export const GET_ERROR_SUCCESS = 'GET_ERROR_SUCCESS';
export const GET_ERROR_FAILURE = 'GET_ERROR_FAILURE';

export const GET_DURATION_START = 'GET_DURATION_START';
export const GET_DURATION_END = 'GET_DURATION_END';
export const GET_DURATION_SUCCESS = 'GET_DURATION_SUCCESS';
export const GET_DURATION_FAILURE = 'GET_DURATION_FAILURE';

export const GET_DURATION_AGENT_START = 'GET_DURATION_AGENT_START';
export const GET_DURATION_AGENT_END = 'GET_DURATION_AGENT_END';
export const GET_DURATION_AGENT_SUCCESS = 'GET_DURATION_AGENT_SUCCESS';
export const GET_DURATION_AGENT_FAILURE = 'GET_DURATION_AGENT_FAILURE';

export const GET_MENU_START = 'GET_MENU_START';
export const GET_MENU_END = 'GET_MENU_END';
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
export const GET_MENU_FAILURE = 'GET_MENU_FAILURE';

export const POST_MENU_START = 'POST_MENU_START';
export const POST_MENU_END = 'POST_MENU_END';
export const POST_MENU_SUCCESS = 'POST_MENU_SUCCESS';
export const POST_MENU_FAILURE = 'POST_MENU_FAILURE';

export const GET_SERVICE_DISTRIBUTION = 'GET_SERVICE_DISTRIBUTION';
export const GET_PERFORMANCE = 'GET_PERFORMANCE';
